"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui_sloting_solution.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/rohuntripathi/Documents/code/mycol.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
